### ISSUE TITLE
Merging project with based.cooking project

### ISSUE THREAD

**Issue by Raymonzut** [obfuscurity/food-recipes#12]
To let these recipes live on in the public domain under a more maintained repo, moving the recipes to [based.cooking](https://based.cooking/), [gh](https://github.com/lukesmithxyz/based.cooking), and archiving this repo seems a good option.

A quick task list would be:
- [ ] Convert each recipe to the new format
- [ ] Link to based.cooking in README
- [ ] Archive this repo
- [ ] PR recipes for based.cooking

**Comment by obfuscurity** [comment]
I appreciate the offer, but no thank you. This repo was always intended to serve as my own resource for tracking personal recipes.
